<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Karnataka State Commercial Vehicle Drivers Insurance</title>
    <!-- Le styles -->
    <link href="/assets/css/bootstrap.css" rel="stylesheet">
    <style>
      body {
        padding-top: 200px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
      .navcolorchange { 
      background-color: red; /* fallback color, place your own */
      } 
    </style>
    <link href="/assets/css/bootstrap-responsive.css" rel="stylesheet">
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <style>
      .navcolorchange { 
  		background-color: #08C;
      } 
      .newfontcolor{
        color: #000;
      }
      .blackfont{
        color: #000;
      }

    </style>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="myshorelogo.png">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="assets/ico/apple-touch-icon-57-precomposed.png">
  </head>

  <body>

    <div class="navbar navbar-fixed-top " style="background:white">
     
        <div class="container">
          <h2 style="text-align:center;color:#08C">ಕರ್ನಾಟಕ ರಾಜ್ಯ ವಾಣಿಜ್ಯ ವಾಹನ ಚಾಲಕರ ಅಪಘಾತ ಪರಿಹಾರ ವಿಮಾ ಯೋಜನೆ</h2>
          <img src="/assets/img/banner.jpg" style="width:120%;height:8.5em;padding-bottom:05px;" alt="banner" class="banner"/>
        </div>
        <div class="container navcolorchange ">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active newfontcolor "><a href="<?php echo $this->url(array('controller'=>'registrations','action'=>'index'),null,true); ?>" >Registrations</a></li>
              <li ><a href="<?php echo $this->url(array('controller'=>'dashboard','action'=>'index'),null,true); ?>" style="color: #fff;" >Dashboard</a></li>
              <li class="custom-disable"><a href="<?php echo $this->url(array('controller'=>'users','action'=>'index'),null,true); ?>" style="color: #fff;">Users</a></li>
            </ul>
            <div class="btn-group pull-right">
	            <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
	              <i class="icon-user"></i> <?php echo $this->userInfo->username; ?>
	              <span class="caret"></span>
	            </a>
	            <ul class="dropdown-menu">
	              <li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'changephone'),null,true); ?>">Change Phone No.</a></li>
	              <li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'changepass'),null,true); ?>">Change Password</a></li>
	              <li class="divider"></li>
	              <li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'logout'),null,true); ?>">Sign Out</a></li>
	            </ul>
          	</div>
	        <div class="btn-group pull-right logged-user-role" style="margin-top:4px">
	            <span class="label label-inverse" ></span>
	        </div>

          </div><!--/.nav-collapse -->
      	</div>
    </div>

    <div class="container">
		<?php echo $this->layout()->content; ?>
    	<hr>
      <footer>
       <p class="copyright">Copyright &copy; 2012 <a href="http://www.myshoreitsolutions.com">MyShore IT Solutions</a>, All Rights Reserved.</p>
      </footer>
    </div>  <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/assets/js/jquery.js"></script>
    <script src="/assets/js/bootstrap-transition.js"></script>
    <script src="/assets/js/bootstrap-alert.js"></script>
    <script src="/assets/js/bootstrap-modal.js"></script>
    <script src="/assets/js/bootstrap-dropdown.js"></script>
    <script src="/assets/js/bootstrap-scrollspy.js"></script>
    <script src="/assets/js/bootstrap-tab.js"></script>
    <script src="/assets/js/bootstrap-tooltip.js"></script>
    <script src="/assets/js/bootstrap-popover.js"></script>
    <script src="/assets/js/bootstrap-button.js"></script>
    <script src="/assets/js/bootstrap-collapse.js"></script>
    <script src="/assets/js/bootstrap-carousel.js"></script>
    <script src="/assets/js/bootstrap-typeahead.js"></script>
    <script src="/assets/js/custom.js"></script>
    <script src="/assets/js/convertor.js"></script>
    <script src="/assets/js/kan.js"></script>

  </body>
</html>



